// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UScOhsGq3NBkkqKseqicKxfDFrQ1Hdg',
    appId: '1:165911995785:web:bbba396228bac2c6bfad58',
    messagingSenderId: '165911995785',
    projectId: 'expense-67b95',
    authDomain: 'expense-67b95.firebaseapp.com',
    storageBucket: 'expense-67b95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6y9hu3WyUfGskKs50Euafefo76jXUtY',
    appId: '1:165911995785:android:4d16603e39ca97d9bfad58',
    messagingSenderId: '165911995785',
    projectId: 'expense-67b95',
    storageBucket: 'expense-67b95.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-UScOhsGq3NBkkqKseqicKxfDFrQ1Hdg',
    appId: '1:165911995785:web:8859a1edec605f68bfad58',
    messagingSenderId: '165911995785',
    projectId: 'expense-67b95',
    authDomain: 'expense-67b95.firebaseapp.com',
    storageBucket: 'expense-67b95.firebasestorage.app',
  );

}